### ISSUE TITLE
Reporting traps (faults) to GDB in SE mode is broken

### ISSUE THREAD

**Issue by janvrany** [gem5/gem5#123] opened 2023-07-26 12:08 UTC
While using gem5 in SE mode I realized that reporting traps to GDB (if connected) is broken / missing at least on 
POWER / RISC-V. 

Consider POWER: https://github.com/gem5/gem5/blob/develop/src/arch/power/faults.cc#L42-L63. `trapToGdb` returns `true` is GDB is connected *and* trap has been reported, otherwise `false`. But the code in `TrapFault::invoke` panics *if* there's a GDB connected and does nothing if there's no GDB at all! I'm pretty sure the logic should be inverse. 

On RISC-V (and possibly other architectures as well) there's no such logic at all, look  at https://github.com/gem5/gem5/blob/develop/src/arch/riscv/faults.cc, so on RISC-V one does not see software breakpoints hitting at all when connecting GDB to debug program running in gem5.

**Comment by janvrany** [comment] 2023-07-26 12:09
I'm working on a fix, will open PR once ready.

**Comment by powerjg** [comment] 2023-07-26 15:03
Seems like a good bug to fix! Thanks for volunteering!

**Comment by shingarov** [comment] 2023-07-26 23:50
I just stepped through it in the debugger — you are absolutely right @janvrany !  Looks like this is a recent regression introduced in https://gem5-review.googlesource.com/c/public/gem5/+/63534

**Comment by powerjg** [comment] 2023-07-27 15:11
Thanks for looking into this, @shingarov!

Looking forward to the PR, @janvrany  ;) Let us know if there's anything we can do to help.

**Comment by janvrany** [comment] 2023-07-27 15:17
@powerjg Thanks, it's "just" a matter of me finding a scrap of time. I'm currently swamped by other work : - ( Hopefully in a week or two,..

**Comment by BobbyRBruce** [comment] 2023-08-22 04:00
Fixed by #166

**Closed as completed by BobbyRBruce** 2023-08-22 04:00 UTC
Labels: bug, sim-se, arch-power, arch-riscv, gdb
