### ISSUE TITLE
gem 5 statistics problem 

### ISSUE THREAD

**Issue by HADOUDA** [gem5/gem5#19] opened 2018-03-10 16:59 UTC
hi, please help me  
-I uploaded the latest version of gem5 in gihub, I executed the following command (./build/X86/gem5.opt configs/example/fs.py --kernel=/media/ali/ali/gem5/full_system/binaries/x86_64-vmlinux-2.6.22.9.smp)with disk image x86root-parsec.img.
i used a .rcs script to run a parsec application eg blackscholes, when i saw the stats file .txt i found several parts of (begin simulation ............ ..and simulation) with deferent information for example the execution time; because I think that in reality I found one part of (begin simulation .... end simulation)
to take the correct execution time .
thank you;

**Comment by cirosantilli-work** [comment] 2018-03-13 09:14
Please close this ticket as a duplicate of: https://github.com/gem5/gem5/issues/17 thanks.

**Closed** 2018-04-08 13:15 UTC
